# Generated by Django 5.0.3 on 2024-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='products/images'),
        ),
    ]
