# Generated by Django 5.0.3 on 2024-03-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rating_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
